FROM golang:1.25-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git

# install air
RUN go install github.com/air-verse/air@latest

# Cache go modules
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

# RUN
CMD ["air"]
